const examples = [
    //Positive
    { "text": "I like javascript", "label": "Positive" },
    { "text": "I love javascript", "label": "Positive" },
    { "text": "I\'m learning javascript", "label": "Positive" },
    { "text": "Javascript is too difficult, but i\'m triying", "label": "Positive" },
    { "text": "I\'m using javascript in my project", "label": "Positive" },
    { "text": "Look what i made with javascript!", "label": "Positive" },
    { "text": "Websites to practice javaScript:\n\n1. Codewars\nhttps://codewars.com\n\n2. JS challenger\nhttps://jschallenger.com\n\n3. W3resource\nhttps://w3resource.com/javascript-exercises/\n\n4. JS hero\nhttps://jshero.net/en/koans/var.html\n\n5. Edabit\nhttps://edabit.com/practice\n\n6. Exercism\nhttps://exercism.org/tracks/javascript", "label": "Positive" },
    { "text": "If it can be done in code, it will be done in JavaScript. https://reddit.com/r/programmerhumor/comments/10hj1m7", "label": "Positive" },
    { "text": "Javascript is too difficult, but i'm triying", "label": "Positive" },
    { "text": "I can't imagine web development without JavaScript.", "label": "Positive" },
    { "text": "JavaScript is so versatile, it can be used for both front-end and back-end development.", "label": "Positive" },
    { "text": "JavaScript is one of the most popular programming languages in the world.", "label": "Positive" },
    { "text": "I find JavaScript to be very expressive and easy to learn.", "label": "Positive" },
    { "text": "JavaScript has a huge community, making it easy to find support and resources.", "label": "Positive" },
    { "text": "I find JavaScript to be very flexible and versatile.", "label": "Positive" },
    { "text": "JavaScript has a vast library of tools and frameworks available.", "label": "Positive" },
    { "text": "I enjoy using JavaScript to create dynamic and interactive websites.", "label": "Positive" },
    { "text": "JavaScript has a strong and growing job market.", "label": "Positive" },
    { "text": "Python is constantly evolving and improving.", "label": "Positive" },
    { "text": "@inerati Ideally, you would want to use both. Python had libraries that can connect to SQL databases for ML.", "label": "Positive" },
    { "text": "#Day24 and #Day25 Solved 2 questions on leetcode Completed python course video And completed SQL course of webdevsimplified #100DaysOfCode #100daysofcodechallenge #programming", "label": "Positive" },
    { "text": "Oracle Database functions to organize and structure datasets to store them electronically in the computerized system. https://t.co/y5wuIxHgpp . #oracle #DataScience #Python #technology #Software #coding #learning #programming #education #business #100DaysOfCode #database", "label": "Positive" },




    //Negative
    { "text": "I hate javascript", "label": "Negative" },
    { "text": "Javascript is too difficult, i don\'t like it", "label": "Negative" },
    { "text": "Javascript is too slow", "label": "Negative" },
    { "text": "I don't want to learn javascript", "label": "Negative" },
    { "text": "Javascript sucks", "label": "Negative" },
    { "text": "I don't like javascript", "label": "Negative" },
    { "text": "JavaScript can be frustrating with its unpredictable behavior and errors.", "label": "Negative" },
    { "text": "JavaScript's syntax can be confusing and counter-intuitive.", "label": "Negative" },
    { "text": "I find that JavaScript is not as performant as other programming languages.", "label": "Negative" },
    { "text": "JavaScript can be quite verbose, making it difficult to write clean and maintainable code.", "label": "Negative" },
    { "text": "JavaScript's security model is flawed and can leave applications vulnerable to attacks.", "label": "Negative" },
    { "text": "I find that debugging JavaScript can be a real hassle.", "label": "Negative" },
    { "text": "JavaScript's event-driven nature can sometimes make code difficult to understand.", "label": "Negative" },
    { "text": "I find that JavaScript's lack of strong typing can lead to unexpected behavior.", "label": "Negative" },
    { "text": "JavaScript's widespread use has also led to a lot of poorly written code and practices.", "label": "Negative" },
    { "text": "I find that JavaScript's dependence on the browser can limit its usage in certain scenarios.", "label": "Negative" },
    //Job Offers
    { "text": "Remote Full Stack Developer (Angular/Node.js) at Avanti Recruitment Avanti Recruitment is partnering with a complex supply chain business with a great... #Javascript #dynamitejobs https://t.co/NH0a2RGbsj", "label": "Job Offers" },
    { "text": "Senior Developer | Java, AWS, Node | Upto £75K | Remote at Opus Recruitment Solutions Role Java Developer Tech Java Springboot AWS TDD Node Location... #Javascript #jobspresso https://t.co/PLhTwpCWC0", "label": "Job Offers" },
    { "text": "Senior Full Stack Javascript Developer at CV Bay Ltd BENEFITS Fully remote Up to £100000 depending on experience 26 days holiday plus bank holidays health and well... #javascript #justremote https://t.co/Qkgzkeeu2a", "label": "Job Offers" },
    { "text": "Javascript Software Engineer 65K Remote Liverpool at Langley James IT Recruitment Javascript Software Engineer upto 65K Remote Role with occasional ... #javascript #weworkremotely https://t.co/BlzBVMuwIh", "label": "Job Offers" },
    { "text": "Senior Software Engineer (React/JavaScript) at CoStar Realty Information, Inc. Senior Software Engineer ReactJavaScript Job Description Job Description CoStar... #reactjs #Hiring https://t.co/4YCTJegOcG", "label": "Job Offers" },
    { "text": "FrontEnd Developer - Remote - Vue at Senitor Associates Ltd FrontEnd Developer Remote Vue Salary 3060K DOE I am looking for an experienced FrontEnd Developer with at l... #javascript #jobs https://t.co/0Zc5kp0YJS", "label": "Job Offers" },
    { "text": "FrontEnd Developer - Remote - Vue at Senitor Associates Ltd FrontEnd Developer Remote Vue Salary 3060K DOE I am looking for an experienced FrontEnd Developer with at l... #javascript #jobs https://t.co/0Zc5kp0YJS", "label": "Job Offers" },
    { "text": "Software Engineer - Full-Stack (React/Node. Js) at Oliver Bernard Software Development Engineer React NodeJSSalary £6000070000Location Fully remote within th... #nodejs #freelancer https://t.co/Jlw3nrqdYa", "label": "Job Offers" },
    { "text": "Full Stack JavaScript Engineer at ABC Tech Co. Full Stack JavaScript Engineer with expertise in React and Node.js needed for fast-growing tech company. Remote work options available. Salary range: $120,000-$150,000. #javascript #remotework", "label": "Job Offers" },
    { "text": "Node.js Developer at XYZ Solutions. Seeking a skilled Node.js developer to join our team. Must have experience with AWS and Express. On-site or remote options available. Pay: $85,000-$110,000. #nodejs #cloudcomputing", "label": "Job Offers" },
    { "text": "JavaScript Front End Engineer at 123 Web Design. Looking for a talented front end engineer with experience in Angular and Vue.js. Full-time remote role. Salary: $90,000-$120,000. #javascript #frontend", "label": "Job Offers" },
    { "text": "Senior Full Stack Developer at Top Code Inc. Senior Full Stack Developer with experience in React, Node.js, and GraphQL needed for innovative software company. Fully remote role. Pay: $140,000-$180,000. #reactjs #graphql", "label": "Job Offers" },
    { "text": "PHP Web Developer at WebWise Solutions. Seeking a skilled PHP developer with experience in Laravel and MySQL. Full-time on-site role. Salary: $70,000-$90,000. #php #laravel", "label": "Job Offers" },
    { "text": "Senior PHP Engineer at CodeCrush Inc. Senior PHP Engineer with expertise in Symfony and REST APIs needed for fast-growing tech company. Remote work options available. Salary range: $120,000-$150,000. #php #symfony", "label": "Job Offers" },
    { "text": "PHP Full Stack Developer at DataDriven. Looking for a talented full stack developer with experience in PHP, React, and MySQL. Full-time remote role. Salary: $90,000-$120,000. #php #fullstack", "label": "Job Offers" },
    { "text": "PHP Software Engineer at NextGen. PHP Software Engineer with experience in CodeIgniter and AWS needed for innovative software company. Fully remote role. Pay: $140,000-$180,000. #php #aws", "label": "Job Offers" },
    { "text": "Solidity Developer at Blockchain Labs. Seeking a skilled Solidity developer to join our team. Must have experience with Ethereum and smart contract development. On-site or remote options available. Pay: $85,000-$110,000. #solidity #blockchain", "label": "Job Offers" },
    { "text": "Go Engineer at FastTrack Solutions. Go Engineer with expertise in cloud computing and microservices needed for fast-growing tech company. Remote work options available. Salary range: $120,000-$150,000. #go #cloudcomputing", "label": "Job Offers" },
    { "text": "Rust Full Stack Developer at IronCode. Looking for a talented full stack developer with experience in Rust, React, and AWS. Full-time remote role. Salary: $90,000-$120,000. #rust #fullstack", "label": "Job Offers" },
    { "text": "Senior Solidity Engineer at SmartChain. Senior Solidity Engineer with experience in Truffle and smart contract security needed for innovative blockchain company. Fully remote role. Pay: $140,000-$180,000. #solidity #truffle", "label": "Job Offers" },
    { "text": "Go Full Stack Developer at GoWeb. Go Full Stack Developer with experience in React and MongoDB needed for fast-growing web development company. On-site role. Salary: $80,000-$100,000. #go #fullstack", "label": "Job Offers" },
    { "text": "Rust Software Engineer at Rustic Systems. Rust Software Engineer with expertise in network programming and concurrent programming needed for innovative software company. Remote role. Pay: $120,000-$150,000. #rust #concurrentprogramming", "label": "Job Offers" },
    { "text": "Direct Contract - IT Strategy and Support - Python Developer at Quanteam, London, £Contract Rate https://t.co/Cng1DxZ3ab Join @contractspy #IT #contracts", "label": "Job Offers" },



    //Spam
    { "text": "🎉Chris is a tech consultant at Booze Allen thanks to Sabio!!🎉 Learn how you can break into tech, too! ⬇️https://t.co/wvCoQSNxZk #Code #Javascript #Job #Hiring #CodeNewbie #Coding #Technology #LearnToCode #Java #Tech #Programming #100DaysofCode #WebDesign #Coding101 https://t.co/tCkEb3SkhK", "label": "Spam" },
    { "text": "We provide the best hands-on training in Graphic Design, Website Design and Development. Phone: 8918-560-266 Our Website: https://t.co/BWPS1EL9Xi #html #css #javascript #programming #coding #webdesign #webdeveloper #webdevelopment #developer #habra #barasat #kolkata #bongaon https://t.co/fruUXxDfhw", "label": "Spam" },
    { "text": "Don't struggle, we are here to help #book review #Assignment #Chemistry #Physics #history #Econometrics #Math #Chem #Biology #Essay English #AcademicTwitter Paper pay #Case study #quiz #Exam #Online class #marketing #Discussion #javascript #Python DM @RealProfession4", "label": "Spam" },
    { "text": "Don't struggle, we are here to help #book review #Assignment #Chemistry #Physics #history #Econometrics #Math #Chem #Biology #Essay English #AcademicTwitter Paper pay #Case study #quiz #Exam #Online class #marketing #Discussion #javascript DM @RealProfession4", "label": "Spam" },
    { "text": "Don't struggle, we are here to help #book review #Assignment #Chemistry #Physics #history #Econometrics #Math #Chem #Biology #Essay English #AcademicTwitter Paper pay #Case study #javascript #Python #php #quiz #Exam #Online class #marketing #Discussion DM @RealProfession4", "label": "Spam" },
    { "text": "✅ Conduct manual technical audits and provide reports ✅ Set up Google Analytics and Search Console with event tracking and data segmentation ✅ Update website content and links for optimal search rankings ✅ Knowledge of HTML, CSS, and JavaScript", "label": "Spam" },
    { "text": "Contact us - 🌐 https://t.co/Pa0GN8DRl0 📧 info@d3mynds.com Call us: - +919953535812 #socialmediamarketing #websitedevelopment #codinglife #socialmedia #DrManmohanSingh #d3mynds #tech #incometax #ux #javascript #HTML #Webdesign #NarendraModi #subhmangill #Budget2023 https://t.co/4HkJlmlUUH", "label": "Spam" },
    { "text": "Buy Instagram Accounts https://t.co/pj9omoLDKH #MachineLearning #DataScience #Python #AI #100DaysOfCode #IoT #flutter #javascript #Serverless #CyberSecurity #localserviceusa #tech #DDoS #DeepLearning #fintech #COVID19 #data #RPA #IIoT #5G #jobs #business #ales #economy #markets", "label": "Spam" },
    { "text": "Buy Trustpilot Reviews https://t.co/NDsYhpVEUt #MachineLearning #DataScience #Python #AI #100DaysOfCode #IoT #flutter #javascript #Serverless #CyberSecurity #localserviceusa #tech #DDoS #DeepLearning #fintech #COVID19 #data #RPA #IIoT #5G #jobs #business #ales #economy #markets", "label": "Spam" },
    { "text": "Buy Verified EBay Accounts https://t.co/dwxliy0Eg8 #MachineLearning #DataScience #Python #AI #100DaysOfCode #IoT #flutter #javascript #Serverless #CyberSecurity #localserviceusa #tech #DDoS #DeepLearning #fintech #COVID19 #data #RPA #IIoT #5G #jobs #business #ales #economy", "label": "Spam" },
    { "text": "Buy Verified Paxful Accounts https://t.co/JjADT0WMB4 #MachineLearning #DataScience #Python #AI #100DaysOfCode #IoT #flutter #javascript #Serverless #CyberSecurity #localserviceusa #tech #DDoS #DeepLearning #fintech #COVID19 #data #RPA #IIoT #5G #jobs #business #ales #economy", "label": "Spam" },
    { "text": "Buy Facebook Reviews https://t.co/K3c9vBQKl3 #MachineLearning #DataScience #Python #AI #100DaysOfCode #IoT #flutter #javascript #Serverless #CyberSecurity #localserviceusa #tech #DDoS #DeepLearning #fintech #COVID19 #data #RPA #IIoT #5G #jobs #business #ales #economy #markets", "label": "Spam" },
    { "text": "Good morning Schedule your appointment today with us for a great massage therapy that will help you feel much better and relaxed https://t.co/hLMG3AIwIY #massage_in_kuwait Fuel Kuwait Southgate #CostOfLivingCrisis #FathersDay #100DaysOfCode #Javascript #coding Zendaya mpesa https://t.co/r2xfvKlCkx", "label": "Spam" },
    { "text": "Free Udemy Certificate Course- Rank Your Blog Website in Google: SEO For Beginners 2023 https://t.co/cKdGKHSHUl #Developers #DEVCommunity #CodeNewbies #100DaysofCode #development #udemy #Coding #Programming #AWS #technology #DataScience #IOT #Javascript #BigData #TensorFlow", "label": "Spam" },

];

export default examples;